/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sftp;

import org.junit.Test;
import static org.junit.Assert.*;

public class ServerTest {
    @Test public void testServerMethod() {
        boolean serverStarted = false;
        Server serverUnderTest = Server
            .builder()
            .port(2222)
            .folder(".")
            .build();
        serverStarted = serverUnderTest.start();
        assertTrue("testServerMethod should return 'true'", serverStarted);
        serverUnderTest.stop();
    }
}
